# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Parquesregios 
email: contacto@parquesregios.com
description: > # this means to ignore newlines until "baseurl:"
    Parques regios una organización sin fines de lucro que busca mejorar la calidad de vida de las personas. Al reabilitar parque como centros de convivencia y ejercicio.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://alfr3dosv.github.io/" # the base hostname & protocol for your site
twitter_username: parquesregios
github_username: parquesregios

# Build settings
markdown: kramdown
